### ISSUE TITLE
Mobile UI

### ISSUE THREAD

**Issue by asadmehdi785** [asadmehdi785/NBA-Trade-Machine#19]
It looks like the current user interface looks a bit weird on mobile, especially for smaller screen sizes. Is there any way we can fix this in our CSS?

**Comment by elassy** [comment]
Adjusted our CSS to give ourselves better margins when viewing on more mobile sites. For the time constraints we had given the semester, we believe that it is more than adequate to deploy for mobile web viewing, however, there are still a few adjustments that could be made.
