### ISSUE TITLE
Pictures for Teams and Players

### ISSUE THREAD

**Issue by DoctorCandor** [asadmehdi785/NBA-Trade-Machine#20]
Pics were removed as of the latest build for stability reasons, we might be able to add them back for the final release.

**Comment by elassy** [comment]
Didn't get a chance to adding team pictures, as we decided it would clutter the dropdown menu. Also, still haven't thought of an elegant way of displaying player pictures.

Our statistic hover box seems like the right place to start - however, wouldn't it just become too cluttered? Seems like it would be taking away from the sleekness, and thus the appeal, of the stats hover box. 

This is an aesthetic feature, one that is far down our list, so we are closing this issue as it does not impact the ability to release the product.
